#!/usr/bin/env python3
"""Generate the C++ header for the Whisper 128-bin mel filterbank.

The Whisper speech tokenizer consumes `whisper.log_mel_spectrogram(speech,
n_mels=128)`, which projects a 400-point STFT power spectrum (201 one-sided
bins) through a precomputed mel filterbank.  That filterbank ships inside the
`openai/whisper` package as `whisper/assets/mel_filters.npz`, generated by
`librosa.filters.mel(sr=16000, n_fft=400, n_mels=128)`.

Rather than reimplement librosa's mel-filter construction (and risk a subtle
parameter drift that would shift token IDs), we embed the *exact* `mel_128`
matrix from that .npz into a C++ header.  This script reads the .npz and emits
the header; the emitted header is committed to the repo, so the build has no
Python/librosa dependency.

Usage:
    python3 tools/gen_mel_filters.py [path/to/mel_filters.npz]
"""

import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_NPZ = os.path.join(ROOT, "tools", "assets", "mel_filters.npz")
OUT_HEADER = os.path.join(ROOT, "src", "dsp", "mel_filters_128.h")


def main() -> int:
    npz_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_NPZ
    with np.load(npz_path, allow_pickle=False) as data:
        if "mel_128" not in data:
            raise SystemExit(f"{npz_path} has no 'mel_128' key; keys={list(data.keys())}")
        mel = data["mel_128"].astype(np.float32)

    assert mel.shape == (128, 201), f"unexpected mel_128 shape {mel.shape}"

    lines = []
    lines.append("// Auto-generated by tools/gen_mel_filters.py.")
    lines.append("// Source: openai/whisper whisper/assets/mel_filters.npz, key 'mel_128'")
    lines.append("//   = librosa.filters.mel(sr=16000, n_fft=400, n_mels=128), float32.")
    lines.append("// Do not edit by hand.  See docs/DSP.md.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace velum::dsp {")
    lines.append("")
    lines.append("inline constexpr int kWhisperNMels = 128;")
    lines.append("inline constexpr int kWhisperNFFTBins = 201;")
    lines.append("")
    lines.append("// Row-major: mel_filter[mel_bin * kWhisperNFFTBins + fft_bin]")
    lines.append("inline const float kWhisperMelFilters[kWhisperNMels * kWhisperNFFTBins] = {")
    def render(v: float) -> str:
        # '.9g' round-trips a float32, but drops the trailing ".0" on whole
        # values (e.g. "0"), which is not a valid C++ floating literal.
        s = f"{v:.9g}"
        if not any(c in s for c in ".eE"):
            s += ".0"
        return s + "f"

    flat = mel.ravel()
    for i in range(0, flat.size, 8):
        chunk = flat[i : i + 8]
        rendered = ", ".join(render(float(v)) for v in chunk)
        lines.append(f"    {rendered},")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace velum::dsp")
    lines.append("")

    with open(OUT_HEADER, "w") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT_HEADER} ({flat.size} floats, {os.path.getsize(OUT_HEADER)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
